/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "1.5.5"
    id("xyz.jpenilla.run-paper") version "2.1.0" // Adds runServer and runMojangMappedServer tasks for testing
    kotlin("jvm") version "1.9.0-RC"
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    paperweight.paperDevBundle("1.20-R0.1-SNAPSHOT")
    implementation(kotlin("stdlib"))
}

group = "dev.cosmics"
version = "1.0"
description = "blockstateanalyzer"
kotlin {
    jvmToolchain(17)
}